export const SUBJECTS = ['Math', 'Algebra', 'Geometry', 'Science', 'Biology', 'Chemistry', 'English', 'Reading'];
export const GRADE_LEVELS = ['Elementary', 'Middle School', 'High School'];

export const tutors = [
  { id: 'maya-chen', name: 'Maya Chen', initials: 'MC', color: '#397d70', subjects: ['Math', 'Algebra', 'Geometry'], gradeLevels: ['Middle School', 'High School'], hourlyRate: 55, bio: 'Maya helps students build confidence with math by breaking big ideas into calm, manageable steps. Her sessions balance clear explanations with plenty of chances to practice.', slots: [{ id: 'maya-0908-400', date: 'Tuesday, September 8', time: '4:00 PM' }, { id: 'maya-0908-530', date: 'Tuesday, September 8', time: '5:30 PM' }, { id: 'maya-0909-330', date: 'Wednesday, September 9', time: '3:30 PM' }, { id: 'maya-0909-600', date: 'Wednesday, September 9', time: '6:00 PM' }] },
  { id: 'leo-martin', name: 'Leo Martin', initials: 'LM', color: '#5573a3', subjects: ['Science', 'Biology', 'Chemistry'], gradeLevels: ['Middle School', 'High School'], hourlyRate: 60, bio: 'Leo makes science feel connected to the world students see every day. He supports organized study habits alongside conceptual understanding in biology and chemistry.', slots: [{ id: 'leo-0908-430', date: 'Tuesday, September 8', time: '4:30 PM' }, { id: 'leo-0909-500', date: 'Wednesday, September 9', time: '5:00 PM' }, { id: 'leo-0910-630', date: 'Thursday, September 10', time: '6:30 PM' }] },
  { id: 'nora-williams', name: 'Nora Williams', initials: 'NW', color: '#a26d50', subjects: ['English', 'Reading'], gradeLevels: ['Elementary', 'Middle School'], hourlyRate: 50, bio: 'Nora creates a supportive space for growing readers and writers. She uses each student’s interests to strengthen comprehension, vocabulary, and clear written expression.', slots: [{ id: 'nora-0908-345', date: 'Tuesday, September 8', time: '3:45 PM' }, { id: 'nora-0909-430', date: 'Wednesday, September 9', time: '4:30 PM' }, { id: 'nora-0910-400', date: 'Thursday, September 10', time: '4:00 PM' }] },
  { id: 'samira-patel', name: 'Samira Patel', initials: 'SP', color: '#8b6a9a', subjects: ['Math', 'Science', 'Reading'], gradeLevels: ['Elementary', 'Middle School'], hourlyRate: 52, bio: 'Samira enjoys helping younger learners become curious, independent problem-solvers. She brings a patient, encouraging approach to foundational math, science, and reading.', slots: [{ id: 'samira-0908-315', date: 'Tuesday, September 8', time: '3:15 PM' }, { id: 'samira-0909-345', date: 'Wednesday, September 9', time: '3:45 PM' }, { id: 'samira-0910-530', date: 'Thursday, September 10', time: '5:30 PM' }] },
  { id: 'owen-reed', name: 'Owen Reed', initials: 'OR', color: '#4e837e', subjects: ['Algebra', 'Geometry', 'Chemistry'], gradeLevels: ['High School'], hourlyRate: 65, bio: 'Owen supports high school students as they tackle demanding coursework with a practical, low-pressure style. He focuses on reasoning through problems and preparing for the next class with a plan.', slots: [{ id: 'owen-0908-600', date: 'Tuesday, September 8', time: '6:00 PM' }, { id: 'owen-0909-700', date: 'Wednesday, September 9', time: '7:00 PM' }, { id: 'owen-0910-515', date: 'Thursday, September 10', time: '5:15 PM' }] }
];

export const findTutor = (id) => tutors.find((tutor) => tutor.id === id);
export const groupedSlots = (tutor) => tutor.slots.reduce((groups, slot) => { (groups[slot.date] ||= []).push(slot); return groups; }, {});
